# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches:
      - master
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci@v1

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: debug-app
          path: app/build/outputs/apk/debug



