# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up jdk11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run ktlint
        run: ./gradlew ktlint

      - name: Run test
        run: ./gradlew testDebugUnitTest

      - name: Run Android Test
        run: ./gradlew assembleDebugAndroidTest

  coverage:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up jdk11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Run createTestCoverage
        uses: ReactiveCircus/android-emulator-runner@v2.21.0
        with:
          api-level: 29
          script: ./gradlew testDebugUnitTestCoverage --stacktrace

      - name: Upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage-result
          path: app/build/reports/coverage/androidTest/debug

