# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up jdk1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Run test
        run : ./gradlew testDebugUnitTest

            
      
